### ISSUE TITLE
Error in Date Time for Exoplanets

### ISSUE THREAD

**Issue by Errabundo66** [rrskybox/TransientSearch#1]
Hello.
I got an error when trying to export the exoplanet file:

Sorry for the long text (in spanish!).
I'm not sure if it's something related to my Regional Spanish time settings.
Thank you
Fernando

Consulte el final de este mensaje para obtener más detalles sobre cómo invocar a la depuración 
Just-In-Time (JIT) en lugar de a este cuadro de diálogo.

************** Texto de la excepción **************
System.ArgumentOutOfRangeException: Los parámetros de año, mes y día describen un campo DateTime que no se puede representar.
   en System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)
   en System.DateTime..ctor(Int32 year, Int32 month, Int32 day)
   en AstroMath.Celestial.JulianToDate(Double julianDays)
   en TransientSDB.Ephemeris.NextTransit(Double julDate, Double periodDays)
   en TransientSDB.Ephemeris.AddCalculatedEphemeris(XElement sdbXResults)
   en TransientSDB.SearchEXO.ServerQueryToResultsXML()
   en TransientSDB.SearchEXO.GetAndSet()
   en TransientSDB.FormTransientSearch.ExoButton_Click(Object sender, EventArgs e)
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   en System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Ensamblados cargados **************
mscorlib
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4515.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
TransientSearch
    Versión del ensamblado: 1.0.0.0
    Versión Win32: 1.0.0.0
    Código base: file:///C:/Users/fhuet_0lr3zv9/AppData/Local/Apps/2.0/CMH3Z4Q0.B5G/M0QOTAEJ.CPP/tran..tion_0000000000000000_0001.0000_164914b86ca3ff8e/TransientSearch.exe
----------------------------------------
System.Windows.Forms
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4515.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4488.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4390.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Deployment
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4270.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Deployment/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Deployment.dll
----------------------------------------
System.Configuration
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4190.0 built by: NET48REL1LAST_B
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4515.0 built by: NET48REL1LAST_C
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4084.0 built by: NET48REL1
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Accessibility
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4084.0 built by: NET48REL1
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------
System.Xml.Linq
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4084.0 built by: NET48REL1
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
AstroMath
    Versión del ensamblado: 1.1.0.0
    Versión Win32: 1.0.0.0
    Código base: file:///C:/Users/fhuet_0lr3zv9/AppData/Local/Apps/2.0/CMH3Z4Q0.B5G/M0QOTAEJ.CPP/tran..tion_0000000000000000_0001.0000_164914b86ca3ff8e/AstroMath.DLL
----------------------------------------
mscorlib.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4084.0 built by: NET48REL1
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_es_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
System.Windows.Forms.resources
    Versión del ensamblado: 4.0.0.0
    Versión Win32: 4.8.4084.0 built by: NET48REL1
    Código base: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_es_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** Depuración JIT **************
Para habilitar la depuración Just In Time (JIT), el archivo de configuración de esta
aplicación o equipo (machine.config) debe tener el
valor jitDebugging establecido en la sección system.windows.forms.
La aplicación también se debe compilar con la depuración
habilitada

Por ejemplo:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Cuando esté habilitada la depuración JIT, cualquier excepción no controlada
se enviará al depurador JIT registrado en el equipo
en lugar de controlarlo mediante el cuadro de diálogo.

**Comment by rrskybox** [comment]
Unable to replicate.  It is possible that the query reply is empty for the Next Transit field.  I will look into adding an exception handler for this case.

**Comment by sco4exoplanets** [comment]
Hi Rick,

Thank you for your reply.  I played around with the install (not being familiar with C+ or Github) and did eventually get it to install correctly.  Your program is great!  Thank you for writing it.

Ed Mullen
Sycamore Canyon Observatory
8990 East Fernbush Court
Vail, Arizona   85641
310-674-2846

________________________________
